import { MongooseModule } from '@nestjs/mongoose'

import {
  AppCodeModel,
  AppCodeSchema,
  AppModel,
  AppSchema,
  AppTokenModel,
  AppTokenSchema,
  BrandKitModel,
  BrandKitSchema,
  CsvShortenJobModel,
  CsvShortenJobSchema,
  EmailTemplateModel,
  EmailTemplateSchema,
  FolderModel,
  FolderSchema,
  FormAnalyticModel,
  FormAnalyticSchema,
  FormLinkModel,
  FormLinkSchema,
  FormModel,
  FormOpenHistoryModel,
  FormOpenHistorySchema,
  FormReportModel,
  FormReportSchema,
  FormSchema,
  IntegrationModel,
  IntegrationSchema,
  ProjectMemberModel,
  ProjectMemberSchema,
  ProjectModel,
  ProjectSchema,
  SubmissionIpLimitModel,
  SubmissionIpLimitSchema,
  SubmissionModel,
  SubmissionSchema,
  TeamActivityModel,
  TeamActivitySchema,
  TeamInvitationModel,
  TeamInvitationSchema,
  TeamMemberModel,
  TeamMemberSchema,
  TeamModel,
  TeamSchema,
  TemplateModel,
  TemplateSchema,
  ThirdPartyOauthModel,
  ThirdPartyOauthSchema,
  UserActivityModel,
  UserActivitySchema,
  UserModel,
  UserSchema,
  UserSocialAccountModel,
  UserSocialAccountSchema
} from './index'

export const ModelModule = MongooseModule.forFeature([
  { name: EmailTemplateModel.name, schema: EmailTemplateSchema },
  { name: FolderModel.name, schema: FolderSchema },
  { name: FormModel.name, schema: FormSchema },
  { name: FormAnalyticModel.name, schema: FormAnalyticSchema },
  { name: FormOpenHistoryModel.name, schema: FormOpenHistorySchema },
  { name: FormReportModel.name, schema: FormReportSchema },
  { name: IntegrationModel.name, schema: IntegrationSchema },
  { name: SubmissionModel.name, schema: SubmissionSchema },
  { name: SubmissionIpLimitModel.name, schema: SubmissionIpLimitSchema },
  { name: TeamModel.name, schema: TeamSchema },
  { name: TeamActivityModel.name, schema: TeamActivitySchema },
  { name: TeamInvitationModel.name, schema: TeamInvitationSchema },
  { name: TeamMemberModel.name, schema: TeamMemberSchema },
  { name: TemplateModel.name, schema: TemplateSchema },
  { name: UserModel.name, schema: UserSchema },
  { name: UserActivityModel.name, schema: UserActivitySchema },
  {
    name: UserSocialAccountModel.name,
    schema: UserSocialAccountSchema
  },
  { name: AppModel.name, schema: AppSchema },
  { name: AppCodeModel.name, schema: AppCodeSchema },
  { name: AppTokenModel.name, schema: AppTokenSchema },
  { name: ThirdPartyOauthModel.name, schema: ThirdPartyOauthSchema },
  { name: ProjectModel.name, schema: ProjectSchema },
  { name: ProjectMemberModel.name, schema: ProjectMemberSchema },
  { name: BrandKitModel.name, schema: BrandKitSchema },
  { name: CsvShortenJobModel.name, schema: CsvShortenJobSchema },
  { name: FormLinkModel.name, schema: FormLinkSchema }
])
