import {
  IconAward,
  IconBookmark,
  IconBriefcase,
  IconBuilding,
  IconCamera,
  IconChartBar,
  IconChecklist,
  IconClipboard,
  IconCrown,
  IconDiamond,
  IconFlag,
  IconFlame,
  IconFolder,
  IconFolderBolt,
  IconFolderCheck,
  IconFolderCode,
  IconFolderCog,
  IconFolderFilled,
  IconFolderHeart,
  IconFolderPin,
  IconFolderShare,
  IconFolderStar,
  IconGift,
  IconHeart,
  IconLeaf,
  IconMedal,
  IconMusic,
  IconNotes,
  IconPalette,
  IconPlant,
  IconPresentation,
  IconReport,
  IconRocket,
  IconStar,
  IconTable
} from '@tabler/icons-react'

export const FOLDER_ICON_MAP = {
  Folder: IconFolder,
  FolderFilled: IconFolderFilled,
  FolderStar: IconFolderStar,
  FolderHeart: IconFolderHeart,
  FolderCode: IconFolderCode,
  FolderBolt: IconFolderBolt,
  FolderCheck: IconFolderCheck,
  FolderPin: IconFolderPin,
  FolderCog: IconFolderCog,
  FolderShare: IconFolderShare,
  Briefcase: IconBriefcase,
  Building: IconBuilding,
  ChartBar: IconChartBar,
  Presentation: IconPresentation,
  Report: IconReport,
  Clipboard: IconClipboard,
  Checklist: IconChecklist,
  Notes: IconNotes,
  Table: IconTable,
  Bookmark: IconBookmark,
  Star: IconStar,
  Heart: IconHeart,
  Rocket: IconRocket,
  Palette: IconPalette,
  Camera: IconCamera,
  Music: IconMusic,
  Flag: IconFlag,
  Gift: IconGift,
  Plant: IconPlant,
  Leaf: IconLeaf,
  Flame: IconFlame,
  Diamond: IconDiamond,
  Crown: IconCrown,
  Medal: IconMedal,
  Award: IconAward
} as const

export type FolderIconName = keyof typeof FOLDER_ICON_MAP

export function getFolderIcon(name?: string) {
  if (!name) return IconFolder
  return (FOLDER_ICON_MAP as Record<string, typeof IconFolder>)[name] ?? IconFolder
}
